[BROKEN] Attempt to render turnout data in summary results
This crashes when calling election.turnout.summary_results(), because
the turnout model doesn't have the same result loading functionality as
the contest model does, and doesn't seem to store the actual result stat
data in the object either.

The crash happens because .summary_results() calls
.load_result_details() which calls ._load_contest_results_data().
The latter is added as an AutoAttr by the contest loader, but not by the
turnout loader.

Error details:

Traceback (most recent call last):
  File "/usr/local/bin/orr", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/orr/scripts/orr_main.py", line 263, in main
    deterministic=deterministic)
  File "/usr/local/lib/python3.6/site-packages/orr/scripts/orr_main.py", line 225, in run
    context=context, test_mode=test_mode)
  File "/usr/local/lib/python3.6/site-packages/orr/scripts/orr_main.py", line 146, in render_template_dir
    context=context, test_mode=test_mode)
  File "/usr/local/lib/python3.6/site-packages/orr/utils.py", line 449, in process_template
    rendered = template.render(context)
  File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "input/template/index.html", line 20, in top-level template code
    {% do subtemplate('results-summary.html', rel_path_template) %}
  File "/usr/local/lib/python3.6/site-packages/orr/templating.py", line 228, in subtemplate
    rel_path_template=rel_path_template, context=context)
  File "/usr/local/lib/python3.6/site-packages/orr/utils.py", line 449, in process_template
    rendered = template.render(context)
  File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "input/extra_templates/extra-1/results-summary.html", line 12, in top-level template code
    <a class="headerlink" href="{{ element_id|to_fragment }}" title="Permalink to this header">¶</a>
  File "input/extra_templates/extra-1/base.html", line 25, in top-level template code
    {% block content %}{% endblock %}
  File "input/extra_templates/extra-1/results-summary.html", line 73, in block "content"
    <td>{{ election.turnout.summary_results(result_stat, vg.id)[0]|format_number }}</td>
  File "/usr/local/lib/python3.6/site-packages/orr/datamodel.py", line 777, in summary_results
    self.load_results_details()
  File "/usr/local/lib/python3.6/site-packages/orr/datamodel.py", line 764, in load_results_details
    self._load_contest_results_data(self)
AttributeError: 'Contest' object has no attribute '_load_contest_results_data'
Traceback (most recent call last):
  File "/home/catrope/.local/bin/orr-docker", line 11, in <module>
    load_entry_point('osv-results-reporter', 'console_scripts', 'orr-docker')()
  File "/home/catrope/git/osvtac/osv-results-reporter/src/orr/scripts/orr_docker.py", line 336, in main
    run_orr(orr_args, image_name=temp_tag, container=container_name)
  File "/home/catrope/git/osvtac/osv-results-reporter/src/orr/scripts/orr_docker.py", line 256, in run_orr
    run_subprocess(args)
  File "/home/catrope/git/osvtac/osv-results-reporter/src/orr/scripts/orr_docker.py", line 107, in run_subprocess
    raise RuntimeError(msg)